### PR TITLE
disable submit buttons with no input

### PR DESCRIPTION
**Pull request by esharri2**
Submit Response and Submit Reply are both disabled if there are no characters in their respective input fields. I also added a "disabled" property to the Button component so I could do this.

### CODE REVIEW

**Comment by IamGiel** [comment]
Evan,

Nice work.

I could still add an empty response, so I added a regex check, to see if the user typed a letter response and also not allow only white space to be a response.  See if theres any issue with my addition. 

Thanks,
Gel

**Comment by esharri2** [comment]
@IamGiel I don't know regex very well. Will have to play around with this later to see if it works. You should just go ahead and merge if you're confident. 

I was considering an "empty response" to be an empty string. The code I wrote disabled the submit button if the value of the input is an empty string. If you're considering other types of responses (e.g. whitespace) to be an empty response, regex seems like a good option.

**Comment by IamGiel** [comment]
Evan, 

I liked how it looks for letter/numbers/spacebar/characters before allowing the button to be clickable.  However, there are some other things.  Like, I cant submit an entry if I press enter then type any comment.  It has to be comment or space first before it allows you to submit.  Which makes sense because we dont want too much empty lines on a response.  BTW, I may implement that on the the response text as well.  For now, lets use this as temp fix for checking user inputs.

**Comment by John95** [comment]
To resolve the conflicts, just accept the incoming changes to the location of Response.js. I put it in the components folder and fixed the links that direct towards it.

**Comment by esharri2** [comment]
Implemented regex to prevent whitespace-only Replies and Responses

**Pull request merged**
